/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;
import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.text.BadLocationException;

/**
 *
 * @author student
 * 
 */
public class mainWindow extends javax.swing.JFrame {
    
    public static final int maxDecimalPlaces = 5;
    
    
    private int teplotaC = 0;
    private int teplotaF = 0;
    private int teplotaK = 273;
    private File soubor;
    jSoubor txt=new jSoubor();
    private String kodovani = "UTF-8";
    private String searchWord = "";
    
    private String lNumber = "";
    private String rNumber = "";
    private String result = "";
    private String valToStore;
    private String valToStoreN1;
    private String valToStoreN2;
    private String actualOperand;
    private Boolean calc = false;
    private Boolean isLastClickNumber = false;
    private Boolean existDot = false;
    private Boolean isNumberFirst = false;
    private int pomocnaPromenaDatovehoTypuInteger;
    private int numberOfDecPlaces = 0;
    private double number1;
    private double number2;
    private double dResult;
    
    /**
     * Creates new form mainWindow
     */
    
    private static String removeLastChar(String str) {
        return str.substring(0,str.length()-1);
    }
    
    public mainWindow() {
        initComponents();
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jEditorPane1.setContentType("text/plain;charset=windows-1250");
        jEditorPane1.getDocument().putProperty("IgnoreCharsetDirective", Boolean.TRUE);
        jEditorPane1.setText(
                "Zkouška Editoru \n \n"
                + "Hello computer! - \u7535\u8111\u4F60\u597D\uFF01\n"
                + "Welcome to Herong's Website!\n"
                + "\u6B22\u8FCE\u4F60\u8BBF\u95EE\u548C\u8363\u7F51\u7AD9"
                + "\uFF01\nwww.herongyang.com\n\n\n"
                + "Welcome to Herong's Website!\n"
                + "\u6B22\u8FCE\u4F60\u8BBF\u95EE\u548C\u8363\u7F51\u7AD9"
                + "\uFF01\nwww.herongyang.com\n\n\n"
                + "Welcome to Herong's Website!\n"
                + "\u6B22\u8FCE\u4F60\u8BBF\u95EE\u548C\u8363\u7F51\u7AD9"
                + "\uFF01\nwww.herongyang.com"
                + "Welcome to Herong's Website!\n"
                + "\u6B22\u8FCE\u4F60\u8BBF\u95EE\u548C\u8363\u7F51\u7AD9"
                + "\uFF01\nwww.herongyang.com" 
                + "Welcome to Herong's Website!\n"
                + "\u6B22\u8FCE\u4F60\u8BBF\u95EE\u548C\u8363\u7F51\u7AD9"
                + "\uFF01\nwww.herongyang.com"
                + "Welcome to Herong's Website!\n"
                + "\u6B22\u8FCE\u4F60\u8BBF\u95EE\u548C\u8363\u7F51\u7AD9"
                + "\uFF01\nwww.herongyang.com"
                + "Welcome to Herong's Website!\n"
                + "\u6B22\u8FCE\u4F60\u8BBF\u95EE\u548C\u8363\u7F51\u7AD9"
                + "\uFF01\nwww.herongyang.com"
                + "Welcome to Herong's Website!\n"
                + "\u6B22\u8FCE\u4F60\u8BBF\u95EE\u548C\u8363\u7F51\u7AD9"
                + "\uFF01\nwww.herongyang.com"
        );
                
    }
    
    private void nastavTeplotu(){
        cSpinner.setValue(teplotaC);
        fSpinner.setValue(teplotaF);
        kSpinner.setValue(teplotaK);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        inputBase = new javax.swing.ButtonGroup();
        outputBase = new javax.swing.ButtonGroup();
        Barvy = new javax.swing.ButtonGroup();
        Kodovani = new javax.swing.ButtonGroup();
        Font = new javax.swing.ButtonGroup();
        jToolBar2 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        tSlider = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cSpinner = new javax.swing.JSpinner();
        kSpinner = new javax.swing.JSpinner();
        fSpinner = new javax.swing.JSpinner();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        input = new javax.swing.JTextField();
        output = new javax.swing.JTextField();
        buttonConvert = new javax.swing.JButton();
        outBIN = new javax.swing.JRadioButton();
        inBIN = new javax.swing.JRadioButton();
        inOCT = new javax.swing.JRadioButton();
        outOCT = new javax.swing.JRadioButton();
        outDEC = new javax.swing.JRadioButton();
        inDEC = new javax.swing.JRadioButton();
        inHEX = new javax.swing.JRadioButton();
        outHEX = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel6 = new javax.swing.JPanel();
        kalkulacka_vysledek = new javax.swing.JTextField();
        smazat = new javax.swing.JButton();
        num7 = new javax.swing.JButton();
        num8 = new javax.swing.JButton();
        num9 = new javax.swing.JButton();
        num4 = new javax.swing.JButton();
        num5 = new javax.swing.JButton();
        num6 = new javax.swing.JButton();
        num1 = new javax.swing.JButton();
        num2 = new javax.swing.JButton();
        num3 = new javax.swing.JButton();
        num0 = new javax.swing.JButton();
        plus = new javax.swing.JButton();
        minus = new javax.swing.JButton();
        krat = new javax.swing.JButton();
        deleno = new javax.swing.JButton();
        tecka = new javax.swing.JButton();
        rovnase = new javax.swing.JButton();
        CE = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane2 = new javax.swing.JEditorPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jRadioButtonMenuItem4 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem5 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem6 = new javax.swing.JRadioButtonMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Marek Kovalčík - aplikace ");
        setAlwaysOnTop(true);
        setPreferredSize(new java.awt.Dimension(700, 500));

        jToolBar2.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikony/document_open.png"))); // NOI18N
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikony/filesave.png"))); // NOI18N
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton2);

        getContentPane().add(jToolBar2, java.awt.BorderLayout.PAGE_START);

        jPanel4.setMaximumSize(new java.awt.Dimension(32767, 20));
        jPanel4.setPreferredSize(new java.awt.Dimension(407, 20));
        jPanel4.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon("M:\\škola\\PCV IT3\\PROGRAMY\\KOVALCIK_PROJEKT_IT3-prog\\KOVALCIK_PROJEKT_IT3-prog\\src\\ikony\\odkaz.jpg")); // NOI18N
        jLabel1.setText("   SŠPU Opava");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel1);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Marek Kovalčík IT3-PRP 2014/2015   ");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel2);

        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_END);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        tSlider.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        tSlider.setMajorTickSpacing(10);
        tSlider.setMaximum(150);
        tSlider.setMinimum(-100);
        tSlider.setMinorTickSpacing(5);
        tSlider.setPaintLabels(true);
        tSlider.setPaintTicks(true);
        tSlider.setToolTipText("");
        tSlider.setValue(0);
        tSlider.setPreferredSize(new java.awt.Dimension(500, 45));
        tSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tSliderStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Voda mrzne !");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Voda vaří !");

        jLabel5.setText("Ferenheit");

        cSpinner.setModel(new javax.swing.SpinnerNumberModel(0, -100, 150, 1));
        cSpinner.setPreferredSize(new java.awt.Dimension(60, 30));

        kSpinner.setModel(new javax.swing.SpinnerNumberModel(273, 173, 423, 1));
        kSpinner.setPreferredSize(new java.awt.Dimension(60, 30));

        fSpinner.setModel(new javax.swing.SpinnerNumberModel(32, -148, 302, 1));
        fSpinner.setPreferredSize(new java.awt.Dimension(60, 30));

        jLabel9.setText("Cesius");

        jLabel10.setText("Kelvin");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(120, 120, 120)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(tSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(fSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addContainerGap(97, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Převodník teplot", jPanel1);

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));

        jLabel6.setBackground(new java.awt.Color(255, 51, 51));
        jLabel6.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Převodník soustav");
        jLabel6.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel6.setDoubleBuffered(true);
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Číslo:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Výsledek:");

        input.setText("0");
        input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputActionPerformed(evt);
            }
        });

        output.setEditable(false);

        buttonConvert.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        buttonConvert.setForeground(new java.awt.Color(0, 0, 255));
        buttonConvert.setText("Převeď!");
        buttonConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConvertActionPerformed(evt);
            }
        });

        outputBase.add(outBIN);
        outBIN.setText("BIN");

        inputBase.add(inBIN);
        inBIN.setText("BIN");

        inputBase.add(inOCT);
        inOCT.setText("OCT");

        outputBase.add(outOCT);
        outOCT.setText("OCT");

        outputBase.add(outDEC);
        outDEC.setText("DEC");

        inputBase.add(inDEC);
        inDEC.setText("DEC");

        inputBase.add(inHEX);
        inHEX.setText("HEX");
        inHEX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inHEXActionPerformed(evt);
            }
        });

        outputBase.add(outHEX);
        outHEX.setText("HEX");
        outHEX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outHEXActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 783, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(output)
                            .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(inBIN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(inOCT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(inDEC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(inHEX))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(outBIN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(outOCT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(outDEC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(outHEX))))
                    .addComponent(buttonConvert, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(175, 175, 175))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inBIN)
                    .addComponent(inOCT)
                    .addComponent(inDEC)
                    .addComponent(inHEX))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outBIN)
                    .addComponent(outOCT)
                    .addComponent(outDEC)
                    .addComponent(outHEX))
                .addGap(18, 18, 18)
                .addComponent(buttonConvert)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Převodník soustav", jPanel2);

        jEditorPane1.setMaximumSize(new java.awt.Dimension(400, 200));
        jScrollPane1.setViewportView(jEditorPane1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane1.getAccessibleContext().setAccessibleParent(jScrollPane1);

        jTabbedPane1.addTab("Textový editor", jPanel5);

        jPanel6.setBackground(new java.awt.Color(102, 255, 102));

        kalkulacka_vysledek.setEditable(false);
        kalkulacka_vysledek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kalkulacka_vysledekActionPerformed(evt);
            }
        });

        smazat.setBackground(new java.awt.Color(255, 255, 102));
        smazat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        smazat.setText("C");
        smazat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smazatActionPerformed(evt);
            }
        });

        num7.setBackground(new java.awt.Color(102, 255, 255));
        num7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        num7.setText("7");
        num7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num7ActionPerformed(evt);
            }
        });

        num8.setBackground(new java.awt.Color(102, 255, 255));
        num8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        num8.setText("8");
        num8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num8ActionPerformed(evt);
            }
        });

        num9.setBackground(new java.awt.Color(102, 255, 255));
        num9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        num9.setText("9");
        num9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num9ActionPerformed(evt);
            }
        });
        num9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                num9KeyPressed(evt);
            }
        });

        num4.setBackground(new java.awt.Color(102, 255, 255));
        num4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        num4.setText("4");
        num4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num4ActionPerformed(evt);
            }
        });

        num5.setBackground(new java.awt.Color(102, 255, 255));
        num5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        num5.setText("5");
        num5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num5ActionPerformed(evt);
            }
        });

        num6.setBackground(new java.awt.Color(102, 255, 255));
        num6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        num6.setText("6");
        num6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num6ActionPerformed(evt);
            }
        });

        num1.setBackground(new java.awt.Color(102, 255, 255));
        num1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        num1.setText("1");
        num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num1ActionPerformed(evt);
            }
        });

        num2.setBackground(new java.awt.Color(102, 255, 255));
        num2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        num2.setText("2");
        num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num2ActionPerformed(evt);
            }
        });

        num3.setBackground(new java.awt.Color(102, 255, 255));
        num3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        num3.setText("3");
        num3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num3ActionPerformed(evt);
            }
        });

        num0.setBackground(new java.awt.Color(102, 255, 255));
        num0.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        num0.setText("0");
        num0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num0ActionPerformed(evt);
            }
        });

        plus.setBackground(new java.awt.Color(255, 255, 102));
        plus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        plus.setText("+");
        plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusActionPerformed(evt);
            }
        });

        minus.setBackground(new java.awt.Color(255, 255, 102));
        minus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        minus.setText("-");
        minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusActionPerformed(evt);
            }
        });

        krat.setBackground(new java.awt.Color(255, 255, 102));
        krat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        krat.setText("*");
        krat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kratActionPerformed(evt);
            }
        });

        deleno.setBackground(new java.awt.Color(255, 255, 102));
        deleno.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        deleno.setText("/");
        deleno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delenoActionPerformed(evt);
            }
        });

        tecka.setBackground(new java.awt.Color(255, 255, 102));
        tecka.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tecka.setText(".");
        tecka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teckaActionPerformed(evt);
            }
        });

        rovnase.setBackground(new java.awt.Color(255, 0, 0));
        rovnase.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rovnase.setText("=");
        rovnase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rovnaseActionPerformed(evt);
            }
        });

        CE.setBackground(new java.awt.Color(255, 255, 102));
        CE.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        CE.setText("CE");
        CE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CEActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon("M:\\škola\\PCV IT3\\PROGRAMY\\KOVALCIK_PROJEKT_IT3-prog\\KOVALCIK_PROJEKT_IT3-prog\\src\\ikony\\kalkulacka_obrazek.png")); // NOI18N
        jLabel11.setToolTipText("");
        jLabel11.setMaximumSize(new java.awt.Dimension(100, 100));
        jLabel11.setMinimumSize(new java.awt.Dimension(100, 100));
        jLabel11.setPreferredSize(new java.awt.Dimension(100, 100));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tekton Pro Cond", 1, 36)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Jednoduchá kalkulačka");
        jLabel12.setToolTipText("");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(kalkulacka_vysledek, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rovnase, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(CE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tecka, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(num1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(num7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(num4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(num5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(num8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(num2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(num0, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(num9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(num6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(num3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(smazat, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(minus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(krat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(deleno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(plus, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kalkulacka_vysledek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rovnase)
                            .addComponent(CE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(num7)
                            .addComponent(num9)
                            .addComponent(plus)
                            .addComponent(num8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(num4)
                                .addComponent(num5))
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(num6)
                                .addComponent(minus)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(num1)
                                    .addComponent(num3)
                                    .addComponent(krat))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(deleno)
                                    .addComponent(tecka)
                                    .addComponent(smazat)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(num2)
                                .addGap(18, 18, 18)
                                .addComponent(num0)))))
                .addGap(61, 61, 61))
        );

        jTabbedPane1.addTab("Kalkulačka", jPanel6);

        jPanel7.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setViewportView(jEditorPane2);

        jPanel7.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Historie úkonů v kalkulačce", jPanel7);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        jMenu1.setMnemonic('s');
        jMenu1.setText("Soubor");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon("M:\\škola\\PCV IT3\\PROGRAMY\\KOVALCIK_PROJEKT_IT3-prog\\KOVALCIK_PROJEKT_IT3-prog\\src\\ikony\\otevrit.jpg")); // NOI18N
        jMenuItem1.setMnemonic('o');
        jMenuItem1.setText("Otevřít...");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon("M:\\škola\\PCV IT3\\PROGRAMY\\KOVALCIK_PROJEKT_IT3-prog\\KOVALCIK_PROJEKT_IT3-prog\\src\\ikony\\ulozit.jpg")); // NOI18N
        jMenuItem2.setMnemonic('u');
        jMenuItem2.setText("Uložit...");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator1);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon("M:\\škola\\PCV IT3\\PROGRAMY\\KOVALCIK_PROJEKT_IT3-prog\\KOVALCIK_PROJEKT_IT3-prog\\src\\ikony\\konec.jpg")); // NOI18N
        jMenuItem3.setMnemonic('k');
        jMenuItem3.setText("Konec");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu6.setText("Editace");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setIcon(new javax.swing.ImageIcon("M:\\škola\\PCV IT3\\PROGRAMY\\KOVALCIK_PROJEKT_IT3-prog\\KOVALCIK_PROJEKT_IT3-prog\\src\\ikony\\vybratvse.jpg")); // NOI18N
        jMenuItem4.setText("Vybrat vše");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem4);
        jMenu6.add(jSeparator3);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setIcon(new javax.swing.ImageIcon("M:\\škola\\PCV IT3\\PROGRAMY\\KOVALCIK_PROJEKT_IT3-prog\\KOVALCIK_PROJEKT_IT3-prog\\src\\ikony\\kapirovat.jpg")); // NOI18N
        jMenuItem5.setText("Kopírovat");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem5);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setIcon(new javax.swing.ImageIcon("M:\\škola\\PCV IT3\\PROGRAMY\\KOVALCIK_PROJEKT_IT3-prog\\KOVALCIK_PROJEKT_IT3-prog\\src\\ikony\\vyjmout.jpg")); // NOI18N
        jMenuItem6.setText("Vyjmout");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem6);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setIcon(new javax.swing.ImageIcon("M:\\škola\\PCV IT3\\PROGRAMY\\KOVALCIK_PROJEKT_IT3-prog\\KOVALCIK_PROJEKT_IT3-prog\\src\\ikony\\vlozit.jpg")); // NOI18N
        jMenuItem7.setText("Vložit");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem7);
        jMenu6.add(jSeparator2);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem8.setIcon(new javax.swing.ImageIcon("M:\\škola\\PCV IT3\\PROGRAMY\\KOVALCIK_PROJEKT_IT3-prog\\KOVALCIK_PROJEKT_IT3-prog\\src\\ikony\\hledat.jpg")); // NOI18N
        jMenuItem8.setText("Najít");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem8);

        jMenuBar1.add(jMenu6);

        jMenu2.setMnemonic('n');
        jMenu2.setText("Nastavení");

        jMenu3.setIcon(new javax.swing.ImageIcon("M:\\škola\\PCV IT3\\PROGRAMY\\KOVALCIK_PROJEKT_IT3-prog\\KOVALCIK_PROJEKT_IT3-prog\\src\\ikony\\barvatextu.jpg")); // NOI18N
        jMenu3.setText("Barvy pozadí");

        jMenuItem9.setText("Převodník teplot ...");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem9);

        jMenuItem10.setText("Převodník sousta ...");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem10);

        jMenuItem11.setText("Textový editor ...");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem11);

        jMenu2.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon("M:\\škola\\PCV IT3\\PROGRAMY\\KOVALCIK_PROJEKT_IT3-prog\\KOVALCIK_PROJEKT_IT3-prog\\src\\ikony\\kodovani.jpg")); // NOI18N
        jMenu4.setText("Kódování textu");

        Kodovani.add(jRadioButtonMenuItem4);
        jRadioButtonMenuItem4.setSelected(true);
        jRadioButtonMenuItem4.setText("UTF-8");
        jRadioButtonMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jRadioButtonMenuItem4);

        Kodovani.add(jRadioButtonMenuItem5);
        jRadioButtonMenuItem5.setText("Windows-1250");
        jRadioButtonMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jRadioButtonMenuItem5);

        Kodovani.add(jRadioButtonMenuItem6);
        jRadioButtonMenuItem6.setText("iso8859-2");
        jRadioButtonMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jRadioButtonMenuItem6);

        jMenu2.add(jMenu4);

        jMenuItem12.setIcon(new javax.swing.ImageIcon("M:\\škola\\PCV IT3\\PROGRAMY\\KOVALCIK_PROJEKT_IT3-prog\\KOVALCIK_PROJEKT_IT3-prog\\src\\ikony\\font.jpg")); // NOI18N
        jMenuItem12.setText("Font ...");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem12);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Kalkulačka");

        jMenuItem13.setIcon(new javax.swing.ImageIcon("M:\\škola\\PCV IT3\\PROGRAMY\\KOVALCIK_PROJEKT_IT3-prog\\KOVALCIK_PROJEKT_IT3-prog\\src\\ikony\\ulozithistoriikalulacky.jpg")); // NOI18N
        jMenuItem13.setText("Uložit historii...");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem13);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.jMenuItem2ActionPerformed(evt);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try{
            JFileChooser fc = new JFileChooser();
            fc.setDialogTitle("Otevření souboru");
            fc.setDialogType(JFileChooser.OPEN_DIALOG);
            fc.setCurrentDirectory(new java.io.File("."));
            FileNameExtensionFilter mujFiltr = new FileNameExtensionFilter("Text","txt");
                    fc.setFileFilter(mujFiltr);
            if(fc.showOpenDialog(this)==JFileChooser.APPROVE_OPTION) {
                soubor = fc.getSelectedFile();
                try{
                if(txt.nactiProudZeSouboru(soubor, "UTF-8"))
                    jEditorPane1.setText(txt.s);
            }  
                catch(Exception ex){
                
                    JOptionPane.showMessageDialog(this,"Nastala chyba při načítání souboru","CHyba!",JOptionPane.ERROR_MESSAGE);
                }
            }
                 
        }
        catch(Exception e){
             JOptionPane.showMessageDialog(this,"Nastala chyb při načítání souboru!","CHyba!",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void outHEXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outHEXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outHEXActionPerformed

    private void inHEXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inHEXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inHEXActionPerformed

    private void buttonConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConvertActionPerformed
        int inBase = 0;
        int outBase;
        // TODO add your handling code here:
        if(inBIN.isSelected())
        inBase=2;
        else if(inOCT.isSelected())
        inBase=8;
        else if(inDEC.isSelected())
        inBase=10;
        else
        inBase=16;
        if(outBIN.isSelected())
        outBase=2;
        else if(outOCT.isSelected())
        outBase=8;
        else if(outDEC.isSelected())
        outBase=10;
        else
        outBase=16;
        output.setText(Prevody.convertNumber(input.getText(), inBase, outBase));
        if(Prevody.isValidNumber(input.getText(), inBase))
        output.setText(Prevody.convertNumber(input.getText(),inBase, outBase));
        else{
            JOptionPane.showMessageDialog(this,"Neplatné číslo","CHYBA",JOptionPane.ERROR_MESSAGE);
            output.setText("ERORR");
        }
        /*if(input.getText()==NULL){
            JOptionPane.showMessageDialog(this,"Nebylo zadáno žádné číslo.","CHYBA",JOptionPane.ERROR_MESSAGE);
            output.setText("ERORR");
        }*/
    }//GEN-LAST:event_buttonConvertActionPerformed

    private void inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputActionPerformed

    private void tSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tSliderStateChanged
        teplotaC = tSlider.getValue();
        teplotaK = teplotaC + 273;
        teplotaF = (Integer) ((teplotaC * 9 / 5) + 32);
        if (teplotaC >= 100) {
            jLabel4.setVisible(true);
        } else {
            jLabel4.setVisible(false);
        }
        if (teplotaC < 0) {
            jLabel3.setVisible(true);
        } else {
            jLabel3.setVisible(false);
        }
        nastavTeplotu();
    
        // TODO add your handling code here:
    }//GEN-LAST:event_tSliderStateChanged

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        try{
            JFileChooser fc = new JFileChooser();
            fc.setDialogTitle("Uložení Souboru");
            fc.setDialogType(JFileChooser.SAVE_DIALOG);
            fc.setCurrentDirectory(new java.io.File("."));
            FileNameExtensionFilter mujFiltr = new FileNameExtensionFilter("Text","txt");
                    fc.setFileFilter(mujFiltr);
            if(fc.showSaveDialog(this)==JFileChooser.APPROVE_OPTION) {
                soubor = fc.getSelectedFile();
                try{
                if(txt.ulozProudDoSouboru(fc.getSelectedFile(),jEditorPane1.getText(),kodovani));
            }  
                catch(Exception ex){
                
                    JOptionPane.showMessageDialog(this,"Nastala chyba při načítání souboru","CHyba!",JOptionPane.ERROR_MESSAGE);
                }
            }
                 
        }
        catch(Exception e){
             JOptionPane.showMessageDialog(this,"Nastala chyb při načítání souboru!","CHyba!",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        jEditorPane1.copy();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        jEditorPane1.paste();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        jEditorPane1.requestFocusInWindow();
        jEditorPane1.selectAll();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        jEditorPane1.cut();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jRadioButtonMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem4ActionPerformed
        kodovani="UTF-8";
    }//GEN-LAST:event_jRadioButtonMenuItem4ActionPerformed

    private void jRadioButtonMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem5ActionPerformed
        kodovani="cp1250";
    }//GEN-LAST:event_jRadioButtonMenuItem5ActionPerformed

    private void jRadioButtonMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem6ActionPerformed
        kodovani="iso8859-2";
    }//GEN-LAST:event_jRadioButtonMenuItem6ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        Color barva = JColorChooser.showDialog(this,"Vyber barvu pozadí převodníku teplot",  jPanel1.getBackground());
        jPanel1.setBackground(barva);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
       jEditorPane1.requestFocusInWindow();
        int startFrom = (jEditorPane1.getCaretPosition()==jEditorPane1.getDocument().getLength()) ? 0 : jEditorPane1.getCaretPosition();
        int max = jEditorPane1.getDocument().getLength()- startFrom;
        searchWord = JOptionPane.showInputDialog ("Zadej hledaný řetězec",searchWord);
        int searchIndex = -1;
        try {
            searchIndex = jEditorPane1.getDocument().getText(startFrom, max).indexOf(searchWord);
        } catch (BadLocationException ex) {
            Logger.getLogger(mainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (searchIndex != -1) {
            jEditorPane1.select(searchIndex + startFrom, searchIndex + startFrom + searchWord.length());
        } else {
            JOptionPane.showMessageDialog (this,"Řetězec nebyl nalezen");
            jEditorPane1.setSelectionStart(-1);
            jEditorPane1.setSelectionEnd(-1); 
        }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.jMenuItem1ActionPerformed(evt);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
       GUI.JFontDialog fontDialog =  new GUI.JFontDialog(this,true,jEditorPane1.getFont(),jEditorPane1.getForeground());
        fontDialog.setVisible(true);
        jEditorPane1.setFont(fontDialog.getPismo());
        jEditorPane1.setForeground(fontDialog.getBarva());
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        Color barva = JColorChooser.showDialog(this,"Vyber barvu pozadí převodníku teplot",  jPanel2.getBackground());
        jPanel2.setBackground(barva);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        Color barva = JColorChooser.showDialog(this,"Vyber barvu pozadí převodníku teplot",  jPanel3.getBackground());
        jPanel3.setBackground(barva);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void smazatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smazatActionPerformed
        if(result != "MATH ERROR") {
            if(calc) {
                if(rNumber.length() > 0) {
                    if(rNumber.charAt(rNumber.length() - 1) == '.')
                        existDot = false;
                    else {
                        if(existDot)
                            numberOfDecPlaces--;
                    }    
                    rNumber = removeLastChar(rNumber);
                    result = removeLastChar(result);
                    kalkulacka_vysledek.setText(result);
                }
            }
            else {
                if(lNumber.length() > 0) {
                    if(lNumber.charAt(lNumber.length() - 1) == '.')
                        existDot = false;
                    else {
                        if(existDot)
                            numberOfDecPlaces--;
                    }  
                    lNumber = removeLastChar(lNumber);
                    result = removeLastChar(result);
                    kalkulacka_vysledek.setText(result);
                }
            }
        }
    }//GEN-LAST:event_smazatActionPerformed

    private void num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num1ActionPerformed
        if(result != "MATH ERROR") {
            if(numberOfDecPlaces < maxDecimalPlaces) {
                if(calc)
                    rNumber += "1";
                else
                    lNumber += "1";
                result += "1";
                kalkulacka_vysledek.setText(result);
                isLastClickNumber = true;
                if(existDot)
                    numberOfDecPlaces++;
            }
        }
    }//GEN-LAST:event_num1ActionPerformed

    private void num3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num3ActionPerformed
        if(result != "MATH ERROR") {
            if(numberOfDecPlaces < maxDecimalPlaces) {
                if(calc)
                    rNumber += "3";
                else
                    lNumber += "3";
                result += "3";
                kalkulacka_vysledek.setText(result);
                isLastClickNumber = true;
                if(existDot)
                    numberOfDecPlaces++;
            }
        }
    }//GEN-LAST:event_num3ActionPerformed

    private void num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num2ActionPerformed
        if(result != "MATH ERROR") {
            if(numberOfDecPlaces < maxDecimalPlaces) {
                if(calc)
                    rNumber += "2";
                else
                    lNumber += "2";
                result += "2";
                kalkulacka_vysledek.setText(result);
                isLastClickNumber = true;
                if(existDot)
                    numberOfDecPlaces++;
            }
        }
    }//GEN-LAST:event_num2ActionPerformed

    private void num4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num4ActionPerformed
        if(result != "MATH ERROR") {
            if(numberOfDecPlaces < maxDecimalPlaces) {
                if(calc)
                    rNumber += "4";
                else
                    lNumber += "4";
                result += "4";
                kalkulacka_vysledek.setText(result);
                isLastClickNumber = true;
                if(existDot)
                    numberOfDecPlaces++;
            }
        }
    }//GEN-LAST:event_num4ActionPerformed

    private void plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusActionPerformed
        if(result != "MATH ERROR") {
            if(isLastClickNumber) {
                if(calc) {
                    number1 = Float.parseFloat(lNumber);
                    number2 = Float.parseFloat(rNumber);
                    if(actualOperand == "/" && number2 == 0) {
                        result = "MATH ERROR";
                        kalkulacka_vysledek.setText(result);
                    } 
                    else {
                        switch(actualOperand) {
                            case "/": 
                                dResult = number1 / number2;
                                break;
                            case "*":
                                dResult = number1 * number2;
                                break;
                            case "+":
                                dResult = number1 + number2;
                                break;
                            case "-":
                                dResult = number1 - number2;
                                break;
                        }   
                        dResult *= 100000;
                        dResult = Math.round(dResult);
                        dResult = dResult /100000;
                        pomocnaPromenaDatovehoTypuInteger = (int) dResult;
                        valToStore = (pomocnaPromenaDatovehoTypuInteger == dResult) ? String.valueOf(pomocnaPromenaDatovehoTypuInteger) : String.valueOf(dResult);
                        System.out.println(valToStore);
                        // historie
                        number1 *= 100000;
                        number1 = Math.round(number1);
                        number1 = number1 /100000;
                        number2 *= 100000;
                        number2 = Math.round(number2);
                        number2 = number2 /100000;
                        pomocnaPromenaDatovehoTypuInteger = (int) number1;
                        valToStoreN1 = (pomocnaPromenaDatovehoTypuInteger == number1) ? String.valueOf(pomocnaPromenaDatovehoTypuInteger) : String.valueOf(number1);
                        pomocnaPromenaDatovehoTypuInteger = (int) number2;
                        valToStoreN2 = (pomocnaPromenaDatovehoTypuInteger == number2) ? String.valueOf(pomocnaPromenaDatovehoTypuInteger) : String.valueOf(number2);   
                        jEditorPane2.setText(jEditorPane2.getText()+valToStoreN1+" "+actualOperand+" "+valToStoreN2+" = "+valToStore+System.getProperty("line.separator"));
                        //
                        number1 = Float.parseFloat(valToStore);
                        lNumber = valToStore;
                        rNumber = "";
                        result = "";
                        result += valToStore+" + ";
                        isLastClickNumber = false;
                        kalkulacka_vysledek.setText(result);
                        existDot = false;
                        actualOperand = "+";
                        numberOfDecPlaces = 0;
                    }
                }
                else {
                    calc = true;
                    result += " + ";
                    kalkulacka_vysledek.setText(result);
                    isLastClickNumber = false;
                    existDot = false;
                    actualOperand = "+";
                    numberOfDecPlaces = 0;
                }
            }
        }
    }//GEN-LAST:event_plusActionPerformed

    private void teckaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teckaActionPerformed
        if(result != "MATH ERROR") {
            if(existDot) {
            }
            else {
               
                if(calc) {
                    if(rNumber != null && !rNumber.isEmpty()) {
                        rNumber += ".";
                        existDot = true;
                        result += ".";
                        kalkulacka_vysledek.setText(result);
                        isLastClickNumber = false;
                    }
                }
                else {
                    if(lNumber != null && !lNumber.isEmpty()) {
                        lNumber += ".";
                        existDot = true;
                        result += ".";
                        kalkulacka_vysledek.setText(result);
                        isLastClickNumber = false;
                    }
                }

            }
        }
    }//GEN-LAST:event_teckaActionPerformed

    private void num0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num0ActionPerformed
        if(result != "MATH ERROR") {
            if(numberOfDecPlaces < maxDecimalPlaces) {
                if(calc)
                    rNumber += "0";
                else
                    lNumber += "0";
                result += "0";
                kalkulacka_vysledek.setText(result);
                isLastClickNumber = true;
                if(existDot)
                    numberOfDecPlaces++;
            }
        }
    }//GEN-LAST:event_num0ActionPerformed

    private void num5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num5ActionPerformed
        if(result != "MATH ERROR") {
            if(numberOfDecPlaces < maxDecimalPlaces) {
                if(calc)
                    rNumber += "5";
                else
                    lNumber += "5";
                result += "5";
                kalkulacka_vysledek.setText(result);
                isLastClickNumber = true;
                if(existDot)
                    numberOfDecPlaces++;
            }
        }
    }//GEN-LAST:event_num5ActionPerformed

    private void num6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num6ActionPerformed
        if(result != "MATH ERROR") {
            if(numberOfDecPlaces < maxDecimalPlaces) {
                if(calc)
                    rNumber += "6";
                else
                    lNumber += "6";
                result += "6";
                kalkulacka_vysledek.setText(result);
                isLastClickNumber = true;
                if(existDot)
                    numberOfDecPlaces++;
            }
        }
    }//GEN-LAST:event_num6ActionPerformed

    private void num7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num7ActionPerformed
        if(result != "MATH ERROR") {
            if(numberOfDecPlaces < maxDecimalPlaces) {
                if(calc)
                    rNumber += "7";
                else
                    lNumber += "7";
                result += "7";
                kalkulacka_vysledek.setText(result);
                isLastClickNumber = true;
                if(existDot)
                    numberOfDecPlaces++;
            }
        }
    }//GEN-LAST:event_num7ActionPerformed

    private void num8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num8ActionPerformed
        if(result != "MATH ERROR") {
            if(numberOfDecPlaces < maxDecimalPlaces) {
                if(calc)
                    rNumber += "8";
                else
                    lNumber += "8";
                result += "8";
                kalkulacka_vysledek.setText(result);
                isLastClickNumber = true;
                if(existDot)
                    numberOfDecPlaces++;
            }
        }
    }//GEN-LAST:event_num8ActionPerformed

    private void num9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num9ActionPerformed
        if(result != "MATH ERROR") {
            if(numberOfDecPlaces < maxDecimalPlaces) {
                if(calc)
                    rNumber += "9";
                else
                    lNumber += "9";
                result += "9";
                kalkulacka_vysledek.setText(result);
                isLastClickNumber = true;
                if(existDot)
                    numberOfDecPlaces++;
            }
        }
    }//GEN-LAST:event_num9ActionPerformed

    private void minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusActionPerformed
        if(result != "MATH ERROR") {
            if(isLastClickNumber) {
                if(calc) {
                    number1 = Float.parseFloat(lNumber);
                    number2 = Float.parseFloat(rNumber);
                    if(actualOperand == "/" && number2 == 0) {
                        result = "MATH ERROR";
                        kalkulacka_vysledek.setText(result);
                    } 
                    else {
                        switch(actualOperand) {
                            case "/":
                                dResult = number1 / number2;
                                break;
                            case "*":
                                dResult = number1 * number2;
                                break;
                            case "+":
                                dResult = number1 + number2;
                                break;
                            case "-":
                                dResult = number1 - number2;
                                break;
                        }
                        dResult *= 100000;
                        dResult = Math.round(dResult);
                        dResult = dResult /100000;
                        pomocnaPromenaDatovehoTypuInteger = (int) dResult;
                        valToStore = (pomocnaPromenaDatovehoTypuInteger == dResult) ? String.valueOf(pomocnaPromenaDatovehoTypuInteger) : String.valueOf(dResult);
                        System.out.println(valToStore);
                        // historie
                        number1 *= 100000;
                        number1 = Math.round(number1);
                        number1 = number1 /100000;
                        number2 *= 100000;
                        number2 = Math.round(number2);
                        number2 = number2 /100000;
                        pomocnaPromenaDatovehoTypuInteger = (int) number1;
                        valToStoreN1 = (pomocnaPromenaDatovehoTypuInteger == number1) ? String.valueOf(pomocnaPromenaDatovehoTypuInteger) : String.valueOf(number1);
                        pomocnaPromenaDatovehoTypuInteger = (int) number2;
                        valToStoreN2 = (pomocnaPromenaDatovehoTypuInteger == number2) ? String.valueOf(pomocnaPromenaDatovehoTypuInteger) : String.valueOf(number2);   
                        jEditorPane2.setText(jEditorPane2.getText()+valToStoreN1+" "+actualOperand+" "+valToStoreN2+" = "+valToStore+System.getProperty("line.separator"));
                        //
                        number1 = Float.parseFloat(valToStore);
                        lNumber = valToStore;
                        rNumber = "";
                        result = "";
                        result += valToStore+" - ";
                        isLastClickNumber = false;
                        kalkulacka_vysledek.setText(result);
                        existDot = false;
                        actualOperand = "-";
                        numberOfDecPlaces = 0;
                    }
                }
                else {
                    calc = true;
                    result += " - ";
                    kalkulacka_vysledek.setText(result);
                    isLastClickNumber = false;
                    existDot = false;
                    actualOperand = "-";
                    numberOfDecPlaces = 0;
                }
            }
        }
    }//GEN-LAST:event_minusActionPerformed

    private void kratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kratActionPerformed
        if(result != "MATH ERROR") {
            if(isLastClickNumber) {
                if(calc) {
                    number1 = Float.parseFloat(lNumber);
                    number2 = Float.parseFloat(rNumber);
                    if(actualOperand == "/" && number2 == 0) {
                        result = "MATH ERROR";
                        kalkulacka_vysledek.setText(result);
                    } 
                    else {
                        switch(actualOperand) {
                            case "/":
                                dResult = number1 / number2;
                                break;
                            case "*":
                                dResult = number1 * number2;
                                break;
                            case "+":
                                dResult = number1 + number2;
                                break;
                            case "-":
                                dResult = number1 - number2;
                                break;
                        }
                        dResult *= 100000;
                        dResult = Math.round(dResult);
                        dResult = dResult /100000;
                        pomocnaPromenaDatovehoTypuInteger = (int) dResult;
                        valToStore = (pomocnaPromenaDatovehoTypuInteger == dResult) ? String.valueOf(pomocnaPromenaDatovehoTypuInteger) : String.valueOf(dResult);
                        System.out.println(valToStore);
                        // historie
                        number1 *= 100000;
                        number1 = Math.round(number1);
                        number1 = number1 /100000;
                        number2 *= 100000;
                        number2 = Math.round(number2);
                        number2 = number2 /100000;
                        pomocnaPromenaDatovehoTypuInteger = (int) number1;
                        valToStoreN1 = (pomocnaPromenaDatovehoTypuInteger == number1) ? String.valueOf(pomocnaPromenaDatovehoTypuInteger) : String.valueOf(number1);
                        pomocnaPromenaDatovehoTypuInteger = (int) number2;
                        valToStoreN2 = (pomocnaPromenaDatovehoTypuInteger == number2) ? String.valueOf(pomocnaPromenaDatovehoTypuInteger) : String.valueOf(number2);   
                        jEditorPane2.setText(jEditorPane2.getText()+valToStoreN1+" "+actualOperand+" "+valToStoreN2+" = "+valToStore+System.getProperty("line.separator"));
                        //
                        number1 = Float.parseFloat(valToStore);
                        lNumber = valToStore;
                        rNumber = "";
                        result = "";
                        result += valToStore+" * ";
                        isLastClickNumber = false;
                        kalkulacka_vysledek.setText(result);
                        existDot = false;
                        actualOperand = "*";
                        numberOfDecPlaces = 0;
                    }
                }
                else {
                    calc = true;
                    result += " * ";
                    kalkulacka_vysledek.setText(result);
                    isLastClickNumber = false;
                    existDot = false;
                    actualOperand = "*";
                    numberOfDecPlaces = 0;
                }
            }
        }
    }//GEN-LAST:event_kratActionPerformed

    private void delenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delenoActionPerformed
        if(result != "MATH ERROR") {
            if(isLastClickNumber) {
                if(calc) {
                    number1 = Float.parseFloat(lNumber);
                    number2 = Float.parseFloat(rNumber);
                    if(actualOperand == "/" && number2 == 0) {
                        result = "MATH ERROR";
                        kalkulacka_vysledek.setText(result);
                    } 
                    else {
                        switch(actualOperand) {
                            case "/":
                                dResult = number1 / number2;
                                break;
                            case "*":
                                dResult = number1 * number2;
                                break;
                            case "+":
                                dResult = number1 + number2;
                                break;
                            case "-":
                                dResult = number1 - number2;
                                break;
                        }
                        dResult *= 100000;
                        dResult = Math.round(dResult);
                        dResult = dResult /100000;

                        pomocnaPromenaDatovehoTypuInteger = (int) dResult;
                        valToStore = (pomocnaPromenaDatovehoTypuInteger == dResult) ? String.valueOf(pomocnaPromenaDatovehoTypuInteger) : String.valueOf(dResult);
                        System.out.println(valToStore);
                        // historie
                        number1 *= 100000;
                        number1 = Math.round(number1);
                        number1 = number1 /100000;
                        number2 *= 100000;
                        number2 = Math.round(number2);
                        number2 = number2 /100000;
                        pomocnaPromenaDatovehoTypuInteger = (int) number1;
                        valToStoreN1 = (pomocnaPromenaDatovehoTypuInteger == number1) ? String.valueOf(pomocnaPromenaDatovehoTypuInteger) : String.valueOf(number1);
                        pomocnaPromenaDatovehoTypuInteger = (int) number2;
                        valToStoreN2 = (pomocnaPromenaDatovehoTypuInteger == number2) ? String.valueOf(pomocnaPromenaDatovehoTypuInteger) : String.valueOf(number2);   
                        jEditorPane2.setText(jEditorPane2.getText()+valToStoreN1+" "+actualOperand+" "+valToStoreN2+" = "+valToStore+System.getProperty("line.separator"));
                        //
                        number1 = Float.parseFloat(valToStore);
                        lNumber = valToStore;
                        rNumber = "";
                        result = "";
                        result += valToStore+" / ";
                        isLastClickNumber = false;
                        kalkulacka_vysledek.setText(result);
                        existDot = false;
                        actualOperand = "/";
                        numberOfDecPlaces = 0;
                    }
                }
                else {
                    calc = true;
                    result += " / ";
                    kalkulacka_vysledek.setText(result);
                    isLastClickNumber = false;
                    existDot = false;
                    actualOperand = "/";
                    numberOfDecPlaces = 0;
                }
            }
        }
    }//GEN-LAST:event_delenoActionPerformed

    private void rovnaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rovnaseActionPerformed
        if(result != "MATH ERROR") {
            if(isLastClickNumber) {
                if(calc) {
                    number1 = Float.parseFloat(lNumber);
                    number2 = Float.parseFloat(rNumber);
                    if(actualOperand == "/" && number2 == 0) {
                        result = "MATH ERROR";
                        kalkulacka_vysledek.setText(result);
                    } 
                    else {
                        switch(actualOperand) {
                            case "/":
                                dResult = number1 / number2;
                                break;
                            case "*":
                                dResult = number1 * number2;
                                break;
                            case "+":
                                dResult = number1 + number2;
                                break;
                            case "-":
                                dResult = number1 - number2;
                                break;
                        }
                        dResult *= 100000;
                        dResult = Math.round(dResult);
                        dResult = dResult /100000;
                        pomocnaPromenaDatovehoTypuInteger = (int) dResult;
                        valToStore = (pomocnaPromenaDatovehoTypuInteger == dResult) ? String.valueOf(pomocnaPromenaDatovehoTypuInteger) : String.valueOf(dResult);
                        System.out.println(valToStore);
                        // historie
                        number1 *= 100000;
                        number1 = Math.round(number1);
                        number1 = number1 /100000;
                        number2 *= 100000;
                        number2 = Math.round(number2);
                        number2 = number2 /100000;
                        pomocnaPromenaDatovehoTypuInteger = (int) number1;
                        valToStoreN1 = (pomocnaPromenaDatovehoTypuInteger == number1) ? String.valueOf(pomocnaPromenaDatovehoTypuInteger) : String.valueOf(number1);
                        pomocnaPromenaDatovehoTypuInteger = (int) number2;
                        valToStoreN2 = (pomocnaPromenaDatovehoTypuInteger == number2) ? String.valueOf(pomocnaPromenaDatovehoTypuInteger) : String.valueOf(number2);   
                        jEditorPane2.setText(jEditorPane2.getText()+valToStoreN1+" "+actualOperand+" "+valToStoreN2+" = "+valToStore+System.getProperty("line.separator"));
                        //
                        number1 = Float.parseFloat(valToStore);
                        lNumber = valToStore;
                        rNumber = "";
                        result = "";
                        result += valToStore;
                        isLastClickNumber = true;
                        kalkulacka_vysledek.setText(result);
                        calc = false;
                        numberOfDecPlaces = 0;
                    }
                }
            }
        }
    }//GEN-LAST:event_rovnaseActionPerformed

    private void CEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CEActionPerformed
        lNumber = "";
        rNumber = "";
        result = "";
        calc = false;
        isLastClickNumber = false;
        existDot = false;
        isNumberFirst = false;
        numberOfDecPlaces = 0;
        kalkulacka_vysledek.setText(result);
        jEditorPane2.setText("");
    }//GEN-LAST:event_CEActionPerformed

    private void kalkulacka_vysledekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kalkulacka_vysledekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kalkulacka_vysledekActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        try{
            JFileChooser fc = new JFileChooser();
            fc.setDialogTitle("Uložení historie");
            fc.setDialogType(JFileChooser.SAVE_DIALOG);
            fc.setCurrentDirectory(new java.io.File("."));
            FileNameExtensionFilter mujFiltr = new FileNameExtensionFilter("Text","txt");
                    fc.setFileFilter(mujFiltr);
            if(fc.showSaveDialog(this)==JFileChooser.APPROVE_OPTION) {
                soubor = fc.getSelectedFile();
                try{
                if(txt.ulozProudDoSouboru(fc.getSelectedFile(),jEditorPane2.getText(),kodovani));
            }  
                catch(Exception ex){
                
                    JOptionPane.showMessageDialog(this,"Nastala chyba při načítání souboru","CHyba!",JOptionPane.ERROR_MESSAGE);
                }
            }
                 
        }
        catch(Exception e){
             JOptionPane.showMessageDialog(this,"Nastala chyb při načítání souboru!","CHyba!",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
       
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        try 
        {
            Desktop.getDesktop().browse(new URL("http://www.strojka.opava.cz").toURI());
        }           
        catch (Exception e) {}
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        try 
        {
            Desktop.getDesktop().browse(new URL("http://www.it1209.sspu-opava.cz").toURI());
        }           
        catch (Exception e) {}
    }//GEN-LAST:event_jLabel2MouseClicked

    private void num9KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_num9KeyPressed
       
    }//GEN-LAST:event_num9KeyPressed
/*převodník soustav*/
    
    
   
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new mainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Barvy;
    private javax.swing.JButton CE;
    private javax.swing.ButtonGroup Font;
    private javax.swing.ButtonGroup Kodovani;
    private javax.swing.JButton buttonConvert;
    private javax.swing.JSpinner cSpinner;
    private javax.swing.JButton deleno;
    private javax.swing.JSpinner fSpinner;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JRadioButton inBIN;
    private javax.swing.JRadioButton inDEC;
    private javax.swing.JRadioButton inHEX;
    private javax.swing.JRadioButton inOCT;
    private javax.swing.JTextField input;
    private javax.swing.ButtonGroup inputBase;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JEditorPane jEditorPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem4;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem5;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JSpinner kSpinner;
    private javax.swing.JTextField kalkulacka_vysledek;
    private javax.swing.JButton krat;
    private javax.swing.JButton minus;
    private javax.swing.JButton num0;
    private javax.swing.JButton num1;
    private javax.swing.JButton num2;
    private javax.swing.JButton num3;
    private javax.swing.JButton num4;
    private javax.swing.JButton num5;
    private javax.swing.JButton num6;
    private javax.swing.JButton num7;
    private javax.swing.JButton num8;
    private javax.swing.JButton num9;
    private javax.swing.JRadioButton outBIN;
    private javax.swing.JRadioButton outDEC;
    private javax.swing.JRadioButton outHEX;
    private javax.swing.JRadioButton outOCT;
    private javax.swing.JTextField output;
    private javax.swing.ButtonGroup outputBase;
    private javax.swing.JButton plus;
    private javax.swing.JButton rovnase;
    private javax.swing.JButton smazat;
    private javax.swing.JSlider tSlider;
    private javax.swing.JButton tecka;
    // End of variables declaration//GEN-END:variables

    private FileNameExtensionFilter newFileNameExtensionFilter(String text, String txt) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private static class txt {
        private static String s;

        private static boolean nactiZeSouboru(File soubor) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public txt() {
        }
    }
}
